Attribute VB_Name = "Module1"
Global high As Long
Global init As String
Global mil As Integer
Global lifes As Integer
Global qwert As Integer
Global hi As Integer
Global zxcv As Integer
Global jkl As Integer
Global asdf As Integer
Global qwerty As Integer
